# Author: Hans Liljestrand <hans@liljestrand.dev>
# Copyright: Secure Systems Group, Aalto University, https://ssg.aalto.fi
#
# This code is released under Apache 2.0 license
#

O_LEVEL = 3

include ../Makefile.common
