# Author: Hans Liljestrand <hans@liljestrand.dev>
# Copyright: Secure Systems Group, Aalto University, https://ssg.aalto.fi
#
# This code is released under Apache 2.0 license
#

LLC_FLAGS += -aarch64-dummy-pa
LDFLAGS += -mllvm -aarch64-dummy-pa

# pull in common configuration
include ../Makefile.common
